var classes = [
    {
        "name": "Loans\\LoanProviding\\Application\\Command\\LoanRepay",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loanId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "money",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Prooph\\Common\\Messaging\\Command",
            "Ramsey\\Uuid\\UuidInterface",
            "Money\\Money",
            "Ramsey\\Uuid\\UuidInterface",
            "Ramsey\\Uuid\\Uuid",
            "Money\\Money",
            "Money\\Currency",
            "Money\\Money"
        ],
        "parents": [
            "Prooph\\Common\\Messaging\\Command"
        ],
        "lcom": 2,
        "length": 19,
        "vocabulary": 8,
        "volume": 57,
        "difficulty": 1.21,
        "effort": 69.21,
        "level": 0.82,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 46.94,
        "number_operators": 2,
        "number_operands": 17,
        "number_operators_unique": 1,
        "number_operands_unique": 7,
        "cloc": 3,
        "loc": 21,
        "lloc": 18,
        "mi": 87.82,
        "mIwoC": 60.19,
        "commentWeight": 27.63,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 36.38,
        "totalStructuralComplexity": 108,
        "totalDataComplexity": 1.14,
        "totalSystemComplexity": 109.14,
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Application\\Command\\LoanRequest",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loanId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "customerId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "money",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dateTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Prooph\\Common\\Messaging\\Command",
            "Ramsey\\Uuid\\UuidInterface",
            "Ramsey\\Uuid\\UuidInterface",
            "Money\\Money",
            "DateTimeImmutable",
            "Ramsey\\Uuid\\UuidInterface",
            "Ramsey\\Uuid\\Uuid",
            "Ramsey\\Uuid\\UuidInterface",
            "Ramsey\\Uuid\\Uuid",
            "Money\\Money",
            "Money\\Currency",
            "Money\\Money",
            "DateTimeImmutable"
        ],
        "parents": [
            "Prooph\\Common\\Messaging\\Command"
        ],
        "lcom": 2,
        "length": 32,
        "vocabulary": 12,
        "volume": 114.72,
        "difficulty": 1.27,
        "effort": 146.01,
        "level": 0.79,
        "bugs": 0.04,
        "time": 8,
        "intelligentContent": 90.14,
        "number_operators": 4,
        "number_operands": 28,
        "number_operators_unique": 1,
        "number_operands_unique": 11,
        "cloc": 4,
        "loc": 30,
        "lloc": 26,
        "mi": 81.38,
        "mIwoC": 54.58,
        "commentWeight": 26.8,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.69,
        "relativeSystemComplexity": 36.69,
        "totalStructuralComplexity": 180,
        "totalDataComplexity": 3.43,
        "totalSystemComplexity": 183.43,
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Application\\LoanProvidingService",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "requestForLoan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "repayLoan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cancelLoan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Loans\\LoanProviding\\Domain\\LoanRepository",
            "Prooph\\ServiceBus\\EventBus",
            "Loans\\LoanProviding\\Domain\\LoanRequestVerifierFactory",
            "Loans\\LoanProviding\\Application\\Command\\LoanRequest",
            "Loans\\LoanProviding\\Domain\\Loan",
            "Loans\\LoanProviding\\Application\\LoanRequestRejected",
            "Loans\\LoanProviding\\Application\\Command\\LoanRepay",
            "Loans\\LoanProviding\\Application\\Command\\CancelLoan"
        ],
        "parents": [],
        "lcom": 3,
        "length": 36,
        "vocabulary": 12,
        "volume": 129.06,
        "difficulty": 4.83,
        "effort": 623.78,
        "level": 0.21,
        "bugs": 0.04,
        "time": 35,
        "intelligentContent": 26.7,
        "number_operators": 7,
        "number_operands": 29,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 21,
        "loc": 53,
        "lloc": 32,
        "mi": 93.51,
        "mIwoC": 52.12,
        "commentWeight": 41.39,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.23,
        "relativeSystemComplexity": 100.23,
        "totalStructuralComplexity": 400,
        "totalDataComplexity": 0.91,
        "totalSystemComplexity": 400.91,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Domain\\Event\\LoanCancelled",
        "interface": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "id",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reason",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Prooph\\EventSourcing\\AggregateChanged",
            "Ramsey\\Uuid\\UuidInterface",
            "static",
            "Ramsey\\Uuid\\Uuid"
        ],
        "parents": [
            "Prooph\\EventSourcing\\AggregateChanged"
        ],
        "lcom": 3,
        "length": 12,
        "vocabulary": 5,
        "volume": 27.86,
        "difficulty": 1.13,
        "effort": 31.35,
        "level": 0.89,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 24.77,
        "number_operators": 3,
        "number_operands": 9,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 63.48,
        "mIwoC": 63.48,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.92,
        "relativeSystemComplexity": 9.92,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 2.75,
        "totalSystemComplexity": 29.75,
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Domain\\Event\\LoanCreated",
        "interface": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "id",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "customerId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "totalAmount",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dateTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Prooph\\EventSourcing\\AggregateChanged",
            "Ramsey\\Uuid\\UuidInterface",
            "Ramsey\\Uuid\\UuidInterface",
            "Money\\Money",
            "DateTimeImmutable",
            "static",
            "Ramsey\\Uuid\\Uuid",
            "Ramsey\\Uuid\\Uuid",
            "Money\\Money",
            "Money\\Currency",
            "Money\\Money",
            "DateTimeImmutable"
        ],
        "parents": [
            "Prooph\\EventSourcing\\AggregateChanged"
        ],
        "lcom": 3,
        "length": 29,
        "vocabulary": 11,
        "volume": 100.32,
        "difficulty": 1.2,
        "effort": 120.39,
        "level": 0.83,
        "bugs": 0.03,
        "time": 7,
        "intelligentContent": 83.6,
        "number_operators": 5,
        "number_operands": 24,
        "number_operators_unique": 1,
        "number_operands_unique": 10,
        "cloc": 0,
        "loc": 24,
        "lloc": 24,
        "mi": 55.74,
        "mIwoC": 55.74,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.73,
        "relativeSystemComplexity": 49.73,
        "totalStructuralComplexity": 245,
        "totalDataComplexity": 3.63,
        "totalSystemComplexity": 248.63,
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 7,
        "instability": 0.88,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Domain\\Event\\LoanPaidOff",
        "interface": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "id",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "money",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Prooph\\EventSourcing\\AggregateChanged",
            "Ramsey\\Uuid\\UuidInterface",
            "Money\\Money",
            "static",
            "Ramsey\\Uuid\\Uuid",
            "Money\\Money",
            "Money\\Currency",
            "Money\\Money"
        ],
        "parents": [
            "Prooph\\EventSourcing\\AggregateChanged"
        ],
        "lcom": 3,
        "length": 16,
        "vocabulary": 7,
        "volume": 44.92,
        "difficulty": 1.08,
        "effort": 48.66,
        "level": 0.92,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 41.46,
        "number_operators": 3,
        "number_operands": 13,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 62.03,
        "mIwoC": 62.03,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.52,
        "relativeSystemComplexity": 36.52,
        "totalStructuralComplexity": 108,
        "totalDataComplexity": 1.57,
        "totalSystemComplexity": 109.57,
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Domain\\Loan",
        "interface": false,
        "methods": [
            {
                "name": "init",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "payoff",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cancel",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCustomerId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTotalAmount",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRemainingAmount",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDateTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "aggregateId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apply",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "canBeCancelled",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 11,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "Prooph\\EventSourcing\\AggregateRoot",
            "Ramsey\\Uuid\\UuidInterface",
            "Ramsey\\Uuid\\UuidInterface",
            "Money\\Money",
            "DateTimeImmutable",
            "self",
            "Loans\\LoanProviding\\Domain\\Event\\LoanCreated",
            "Money\\Money",
            "Loans\\LoanProviding\\Domain\\LoanStatus",
            "LogicException",
            "Loans\\LoanProviding\\Domain\\Event\\LoanPaidOff",
            "Loans\\LoanProviding\\Domain\\LoanFullyPaid",
            "Loans\\LoanProviding\\Domain\\LoanOverPaid",
            "LogicException",
            "Loans\\LoanProviding\\Domain\\Event\\LoanCancelled",
            "Ramsey\\Uuid\\UuidInterface",
            "Ramsey\\Uuid\\UuidInterface",
            "Money\\Money",
            "Money\\Money",
            "DateTimeImmutable",
            "Loans\\LoanProviding\\Domain\\LoanStatus",
            "Prooph\\EventSourcing\\AggregateChanged",
            "Loans\\LoanProviding\\Domain\\LoanStatus",
            "Loans\\LoanProviding\\Domain\\LoanStatus",
            "Loans\\LoanProviding\\Domain\\LoanStatus"
        ],
        "parents": [
            "Prooph\\EventSourcing\\AggregateRoot"
        ],
        "lcom": 2,
        "length": 96,
        "vocabulary": 19,
        "volume": 407.8,
        "difficulty": 19.54,
        "effort": 7969.11,
        "level": 0.05,
        "bugs": 0.14,
        "time": 443,
        "intelligentContent": 20.87,
        "number_operators": 29,
        "number_operands": 67,
        "number_operators_unique": 7,
        "number_operands_unique": 12,
        "cloc": 54,
        "loc": 148,
        "lloc": 94,
        "mi": 78.39,
        "mIwoC": 38.14,
        "commentWeight": 40.25,
        "kanDefect": 0.58,
        "relativeStructuralComplexity": 289,
        "relativeDataComplexity": 0.53,
        "relativeSystemComplexity": 289.53,
        "totalStructuralComplexity": 3468,
        "totalDataComplexity": 6.39,
        "totalSystemComplexity": 3474.39,
        "pageRank": 0.18,
        "afferentCoupling": 4,
        "efferentCoupling": 13,
        "instability": 0.76,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Domain\\LoanRequestVerifier\\Always",
        "interface": false,
        "methods": [
            {
                "name": "isOk",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Loans\\LoanProviding\\Domain\\LoanRequestVerifer",
            "Money\\Money",
            "DateTimeImmutable"
        ],
        "parents": [],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 75.43,
        "mIwoC": 75.43,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Domain\\LoanRequestVerifier\\AndX",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isOk",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Loans\\LoanProviding\\Domain\\LoanRequestVerifer",
            "Money\\Money",
            "DateTimeImmutable"
        ],
        "parents": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 8,
        "volume": 42,
        "difficulty": 3,
        "effort": 126,
        "level": 0.33,
        "bugs": 0.01,
        "time": 7,
        "intelligentContent": 14,
        "number_operators": 4,
        "number_operands": 10,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 7,
        "loc": 25,
        "lloc": 18,
        "mi": 97.4,
        "mIwoC": 60.85,
        "commentWeight": 36.55,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.75,
        "relativeSystemComplexity": 2.75,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 5.5,
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Domain\\LoanRequestVerifier\\LoanPeriodLessThan",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isOk",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Loans\\LoanProviding\\Domain\\LoanRequestVerifer",
            "DateInterval",
            "Money\\Money",
            "DateTimeImmutable",
            "DateTime"
        ],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 7,
        "volume": 28.07,
        "difficulty": 2.63,
        "effort": 73.69,
        "level": 0.38,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 10.69,
        "number_operators": 3,
        "number_operands": 7,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 7,
        "loc": 20,
        "lloc": 13,
        "mi": 105.1,
        "mIwoC": 65.43,
        "commentWeight": 39.67,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Domain\\LoanRequestVerifier\\Never",
        "interface": false,
        "methods": [
            {
                "name": "isOk",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Loans\\LoanProviding\\Domain\\LoanRequestVerifer",
            "Money\\Money",
            "DateTimeImmutable"
        ],
        "parents": [],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 75.43,
        "mIwoC": 75.43,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Domain\\LoanRequestVerifier\\OrX",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isOk",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Loans\\LoanProviding\\Domain\\LoanRequestVerifer",
            "Money\\Money",
            "DateTimeImmutable"
        ],
        "parents": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 8,
        "volume": 42,
        "difficulty": 3,
        "effort": 126,
        "level": 0.33,
        "bugs": 0.01,
        "time": 7,
        "intelligentContent": 14,
        "number_operators": 4,
        "number_operands": 10,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 7,
        "loc": 25,
        "lloc": 18,
        "mi": 97.4,
        "mIwoC": 60.85,
        "commentWeight": 36.55,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.75,
        "relativeSystemComplexity": 2.75,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 5.5,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Domain\\LoanRequestVerifier\\RequestMoneyLessThan",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isOk",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Loans\\LoanProviding\\Domain\\LoanRequestVerifer",
            "Money\\Money",
            "Money\\Money",
            "DateTimeImmutable"
        ],
        "parents": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 6,
        "volume": 23.26,
        "difficulty": 1.75,
        "effort": 40.71,
        "level": 0.57,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 13.29,
        "number_operators": 2,
        "number_operands": 7,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 7,
        "loc": 20,
        "lloc": 13,
        "mi": 105.67,
        "mIwoC": 66,
        "commentWeight": 39.67,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Domain\\LoanRequestVerifierFactory",
        "interface": false,
        "methods": [
            {
                "name": "buildFor",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Ramsey\\Uuid\\UuidInterface",
            "Money\\Money",
            "Loans\\LoanProviding\\Domain\\LoanRequestVerifier\\RequestMoneyLessThan",
            "DateInterval",
            "Loans\\LoanProviding\\Domain\\LoanRequestVerifier\\LoanPeriodLessThan",
            "Loans\\LoanProviding\\Domain\\LoanRequestVerifier\\AndX"
        ],
        "parents": [],
        "lcom": 1,
        "length": 4,
        "vocabulary": 4,
        "volume": 8,
        "difficulty": 0.5,
        "effort": 4,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 1,
        "loc": 9,
        "lloc": 8,
        "mi": 98.53,
        "mIwoC": 73.84,
        "commentWeight": 24.69,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Domain\\LoanStatus",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "MyCLabs\\Enum\\Enum"
        ],
        "parents": [
            "MyCLabs\\Enum\\Enum"
        ],
        "lcom": 0,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 3,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 7,
        "lloc": 7,
        "mi": 76.69,
        "mIwoC": 76.69,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.12,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Infrastructure\\EventBasedLoanRepository",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Loans\\LoanProviding\\Domain\\LoanRepository",
            "Prooph\\EventSourcing\\Aggregate\\AggregateRepository",
            "Loans\\LoanProviding\\Domain\\Loan",
            "Ramsey\\Uuid\\UuidInterface",
            "Loans\\LoanProviding\\Domain\\Loan"
        ],
        "parents": [],
        "lcom": 1,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 2,
        "effort": 67.38,
        "level": 0.5,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 16.84,
        "number_operators": 2,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 7,
        "loc": 24,
        "lloc": 17,
        "mi": 99.45,
        "mIwoC": 62.33,
        "commentWeight": 37.12,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 14,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Loans\\LoanProviding\\Infrastructure\\InMemoryLoanRepository",
        "interface": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "save",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Loans\\LoanProviding\\Domain\\LoanRepository",
            "Loans\\LoanProviding\\Domain\\Loan",
            "Ramsey\\Uuid\\UuidInterface",
            "InvalidArgumentException",
            "Loans\\LoanProviding\\Domain\\Loan"
        ],
        "parents": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 7,
        "volume": 42.11,
        "difficulty": 4.5,
        "effort": 189.5,
        "level": 0.22,
        "bugs": 0.01,
        "time": 11,
        "intelligentContent": 9.36,
        "number_operators": 3,
        "number_operands": 12,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 62.09,
        "mIwoC": 62.09,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    }
]